CREATE TABLE cut_and_run_sample_metadata_table (
	sample_id TEXT PRIMARY KEY,
	genome_assembly VARCHAR(20) DEFAULT 'hg38',
        pipeline_version VARCHAR(20) NOT NULL,
	run_date DATE NOT NULL, 
	mito_chr VARCHAR(20) DEFAULT 'chrM',
	mapq_threshold INT CHECK (mapq_threshold > 0),
	macs2_qvalue FLOAT CHECK (macs2_qvalue BETWEEN 0 AND 1),
	qc_status VARCHAR(10) CHECK (qc_status IN ('pass', 'fail')),
	qc_mapped_reads BIGINT CHECK (qc_mapped_reads > 0),
	qc_alignment_rate FLOAT CHECK (qc_alignment_rate BETWEEN 0 AND 100),
	qc_mito_reads_percent FLOAT CHECK (qc_mito_reads_percent BETWEEN 0 AND 100),
	qc_duplicate_rate FLOAT CHECK (qc_duplicate_rate BETWEEN 0 AND 1),
	qc_fragment_size_median FLOAT CHECK (qc_fragment_size_median > 0),
	qc_frip_score FLOAT CHECK (qc_frip_score BETWEEN 0 AND 1),
	qc_nsc_coefficient FLOAT CHECK (qc_nsc_coefficient >= 1),
	qc_rsc_coefficient FLOAT CHECK (qc_rsc_coefficient >= 0),
	qc_estimated_fragment_length INT CHECK (qc_estimated_fragment_length > 0),
	qc_library_complexity FLOAT CHECK (qc_library_complexity BETWEEN 0 AND 1),
	qc_total_peaks_called BIGINT CHECK (qc_total_peaks_called >= 0),
	qc_peaks_after_blacklist_filter BIGINT CHECK (qc_peaks_after_blacklist_filter >= 0),
        FOREIGN KEY (sample_id) REFERENCES sample_sheet_metadata(sample_id)
      );
